# Generated by Django 3.1.5 on 2021-02-23 19:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
