# Generated by Django 3.1.5 on 2021-02-18 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Publicacion'),
        ),
    ]
